services:
  fedora-42:
    image: docker.io/soldierc4/buildroot-fedora:42
    build:
      context: ./fedora-42
  fedora:
    extends: fedora-42
    image: docker.io/soldierc4/buildroot-fedora:latest
